version: v0.13.0

dsn: env://DSN

serve:
  public:
    base_url: https://${RAILWAY_STATIC_URL}
    port: 4433
    cors:
      enabled: true
  admin:
    base_url: http://0.0.0.0:4434
    port: 4434

selfservice:
  default_browser_return_url: https://${RAILWAY_STATIC_URL}/welcome
  allowed_return_urls:
    - https://${RAILWAY_STATIC_URL}

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://${RAILWAY_STATIC_URL}/error

    settings:
      ui_url: https://${RAILWAY_STATIC_URL}/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://${RAILWAY_STATIC_URL}/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://${RAILWAY_STATIC_URL}/verification
      use: code
      after:
        default_browser_return_url: https://${RAILWAY_STATIC_URL}/welcome

    logout:
      after:
        default_browser_return_url: https://${RAILWAY_STATIC_URL}/login

    login:
      ui_url: https://${RAILWAY_STATIC_URL}/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://${RAILWAY_STATIC_URL}/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: info
  format: json

secrets:
  cookie:
    - ${COOKIE_SECRET}
  cipher:
    - ${CIPHER_SECRET}

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: ""

feature_flags:
  use_continue_with_transitions: true
