dsn: sqlite://foo.db?mode=memory&_fk=true

selfservice:
  default_browser_return_url: http://return-to-3-test.ory.sh/

identity:
  default_schema_id: other
  schemas:
    - id: other
      url: file://stub/.identity.invalid.json

courier:
  smtp:
    connection_uri: smtp://foo:bar@baz/
